In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.6 MB 2.8 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/12.6 MB 2.1 MB/s eta 0:00:06
   ---- ----------------------------------- 1.6/12.6 MB 2.3 MB/s eta 0:00:05
   ----- ---------------------------------- 1.8/12.6 MB 2.0 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.6 MB 1.9 MB/s eta 0:00:06
   ------- -------------------------------- 2.4/12.6 MB 1.8 MB/s eta 0:00:06
   --------- ------------------------------ 2.9/12.6 MB 1.8 MB/s eta 0:00:06
   --------- ------------------------------ 3.1/12.6 MB 1.8 MB/s eta 0:00:06
   ----------- ---------------------------- 3.7/12.6 MB 1.8 MB/s eta 0:00:05
   ------------ --------------------------- 3.9/12.6 MB 1.8 MB/s eta 0:00:05
   ------------- -------------------------- 4.2/12.6 MB 1.8 MB/s eta 0:00:05
   ----------

In [3]:
import numpy as np

In [4]:
#creating arrays
arr1 = np.array([1,2,3])

In [5]:
arr1

array([1, 2, 3])

In [6]:
type(arr1)

numpy.ndarray

In [8]:
arr1.shape

(3,)

In [9]:
arr2=arr1.reshape(1,3)

In [10]:
arr2

array([[1, 2, 3]])

In [11]:
arr2.shape()

TypeError: 'tuple' object is not callable

In [12]:
arr2.shape

(1, 3)

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [16]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
#how to create identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
#some imporatant attributes of numpy arrays
arr1.ndim

1

In [19]:
arr2.ndim

2

In [20]:
arr2.size

3

In [21]:
arr2.dtype

dtype('int64')

In [22]:
arr2.itemsize

8

In [25]:
#vectorized operatons

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

In [26]:
print("addition",arr1+arr2)

addition [11 22 33 44 55]


In [27]:
#universal function
np.sqrt(arr1)
np.exp(arr1)
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [28]:
#calculating the mean and standard deviation and doing normalization

mean=np.mean(arr1)

In [29]:
mean

np.float64(3.0)

In [30]:
std_dev = np.std(arr1)

In [31]:
std_dev

np.float64(1.4142135623730951)

In [33]:
normalized_data = (arr1-mean)/std_dev

In [34]:
normalized_data

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [35]:
# normalization is a way to convert data's mean to 0 and standard deviation to 1