# Numpy

In [4]:
import numpy as np

In [5]:
#how to create identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
arr=np.array([[1,2,3],[4,5,6]])

In [11]:
#attributes of numpy arrays
arr.shape
arr.ndim
arr.size
arr.dtype


dtype('int64')

In [12]:
#numpy vectorization operations

arr1=np.array([1,2,3,4,5])
arr2=np.arange(0,50,10)

In [13]:
arr2.size

5

In [14]:
print("addition",arr1+arr2)

addition [ 1 12 23 34 45]


In [18]:
#Universal function
np.sqrt(arr1)
np.exp(arr1)
np.sin(arr1)
np.log(arr1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [19]:
# finding mean , standard deviation and doing normalization
mean = np.mean(arr1)
std = np.std(arr1)
normalized = (arr1-mean)/std
print(normalized)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
